Repository hlxsites/maidenform, pull requests merged in 2022-12, with the labels that each got.

#25 Add footer, copyright, newsletter and footer-links blocks
  blocks/copyright/copyright.css
  blocks/copyright/copyright.js
  blocks/footer-links/footer-links.css
  blocks/footer-links/footer-links.js
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/newsletter/newsletter.css
  blocks/newsletter/newsletter.js
  icons/back-top.svg
  styles/styles.css
  test/blocks/footer/footer.test.js
Labels: frontend

#30 Issue 1 - Default content styling
  fonts/Gilroy-Bold.woff
  fonts/Gilroy-Bold.woff2
  fonts/Gilroy-ExtraBold-Italic.woff
  fonts/Gilroy-ExtraBold-Italic.woff2
  fonts/Gilroy-ExtraBold.woff
  fonts/Gilroy-ExtraBold.woff2
  fonts/Gilroy-Light.woff
  fonts/Gilroy-Light.woff2
  fonts/Gilroy-Medium.woff
  fonts/Gilroy-Medium.woff2
  fonts/Gilroy-Regular.woff
  fonts/Gilroy-Regular.woff2
  fonts/Gilroy-SemiBold.woff
  fonts/Gilroy-SemiBold.woff2
  fonts/Gilroy-UltraLight.woff
  fonts/Gilroy-UltraLight.woff2
  fonts/Zahrah-Bold-Italic.woff
  fonts/Zahrah-Bold-Italic.woff2
  fonts/Zahrah-Bold.woff
  fonts/Zahrah-Bold.woff2
  fonts/Zahrah-Light-Italic.woff
  fonts/Zahrah-Light-Italic.woff2
  fonts/Zahrah-Light.woff
  fonts/Zahrah-Light.woff2
  fonts/Zahrah-Medium-Italic.woff
  fonts/Zahrah-Medium-Italic.woff2
  fonts/Zahrah-Medium.woff
  fonts/Zahrah-Medium.woff2
  fonts/Zahrah-Regular-Italic.woff
  fonts/Zahrah-Regular-Italic.woff2
  fonts/Zahrah-Regular.woff
  fonts/Zahrah-Regular.woff2
  fonts/Zahrah-SemiBold-Italic.woff
  fonts/Zahrah-SemiBold-Italic.woff2
  fonts/Zahrah-SemiBold.woff
  fonts/Zahrah-SemiBold.woff2
  icons/favicon.ico
  scripts/scripts.js
  styles/lazy-styles.css
  styles/styles.css
Labels: frontend

#28 Add footer banner
  blocks/footer-banner/footer-banner.css
  blocks/footer-banner/footer-banner.js
  styles/styles.css
Labels: frontend

#33 Add styles for various column blocks
  blocks/columns/columns.css
  blocks/columns/columns.js
  blocks/hero-video/hero-video.css
  blocks/promo-banner/promo-banner.css
  scripts/lib-franklin.js
  styles/lazy-styles.css
  styles/styles.css
Labels: frontend

#47 Add importer script for category pages
  .gitignore
  package-lock.json
  package.json
  tools/importer/_category-pages.txt
  tools/importer/import.js
Labels: content

#56 Magic of Maidenform Content Page
  blocks/teaser/teaser.css
  styles/styles.css
Labels: content

#60 Rename columns teaser style to overlap
  blocks/columns/columns.css
  blocks/columns/columns.js
Labels: bug

#58 Improve Magic of Maidenform page
  blocks/teaser/teaser.css
  styles/styles.css
Labels: frontend, content
