Repository hlxsites/maidenform, pull requests merged in 2023-04, with the labels that each got.

#199 Add GraphQL schema from QA
  .hlxignore
  schema-qa.graphql
Labels: commerce

#191 homepage 4-10 content
  fragments/2023_04/2023-04-10.html
  styles/lazy-styles.css
  styles/styles.css
Labels: content

#195 Checkout
  .gitignore
  pwa/package.json
  pwa/src/RootComponents/Checkout/checkout.js
  pwa/src/RootComponents/Checkout/index.js
  pwa/src/talons/CheckoutPage/useCheckoutPage.js
  pwa/webpack.config.js
  pwa/yarn.lock
  scripts/pwa-dist/0.js
  scripts/pwa-dist/0.js.map
  scripts/pwa-dist/1.js
  scripts/pwa-dist/1.js.map
  scripts/pwa-dist/2.js
  scripts/pwa-dist/2.js.map
  scripts/pwa-dist/3.js
  scripts/pwa-dist/3.js.map
  scripts/pwa-dist/4.js
  scripts/pwa-dist/4.js.map
  scripts/pwa-dist/5.js
  scripts/pwa-dist/5.js.map
  scripts/pwa-dist/6.js
  scripts/pwa-dist/6.js.map
  scripts/pwa-dist/7.js
  scripts/pwa-dist/7.js.map
  scripts/pwa-dist/8.js
  scripts/pwa-dist/8.js.map
  scripts/pwa-dist/9.js
  scripts/pwa-dist/9.js.map
  scripts/pwa-dist/account.js
  scripts/pwa-dist/account.js.map
  scripts/pwa-dist/cart.js
  scripts/pwa-dist/cart.js.map
  scripts/pwa-dist/checkout.js
  scripts/pwa-dist/checkout.js.map
  scripts/pwa-dist/client.js
  scripts/pwa-dist/client.js.map
  scripts/pwa-dist/login.js
  scripts/pwa-dist/login.js.map
  scripts/pwa-dist/vendors.js
  scripts/pwa-dist/vendors.js.map
  tools/block-picker/dist/index.3ccc1b60.css
  tools/block-picker/dist/index.3ccc1b60.css.map
  tools/block-picker/dist/index.985d9304.js
  tools/block-picker/dist/index.985d9304.js.map
  tools/block-picker/dist/index.html
Labels: commerce

#178 Add Amasty labels to PLP and PDP
  blocks/product-details/ProductDetailsCarousel.js
  blocks/product-details/product-details.css
  blocks/product-details/product-details.js
  blocks/product-list-page/ProductList.js
  blocks/product-list-page/product-list-page.css
  blocks/product-list-page/product-list-page.js
  blocks/product-list-page/productSearch.graphql.js
  scripts/commerce.js
  scripts/reflektion.js
Labels: integrations

#216 Fix: create account page
  pwa/src/components/CreateAccount/createAccount.js
  pwa/src/components/CreateAccount/mutations.gql.js
  pwa/src/talons/CreateAccount/useCreateAccount.js
  pwa/webpack.config.js
  scripts/pwa-dist/account.js
  scripts/pwa-dist/account.js.map
  scripts/pwa-dist/cart.js
  scripts/pwa-dist/cart.js.map
  scripts/pwa-dist/checkout.js
  scripts/pwa-dist/checkout.js.map
  scripts/pwa-dist/client.js
  scripts/pwa-dist/client.js.map
  scripts/pwa-dist/login.js
  scripts/pwa-dist/login.js.map
  scripts/pwa-dist/signup.js
  scripts/pwa-dist/signup.js.map
  scripts/pwa-dist/vendors.js
Labels: commerce

#218 Issue/207: Create Account Page
  pwa/package.json
  pwa/src/RootComponents/CreateAccount/button.module.css
  pwa/src/RootComponents/CreateAccount/createAccount.js
  pwa/src/RootComponents/CreateAccount/createAccount.module.css
  pwa/src/RootComponents/CreateAccount/createAccountPage.js
  pwa/src/RootComponents/CreateAccount/createAccountPage.module.css
  pwa/src/RootComponents/CreateAccount/field.module.css
  pwa/src/RootComponents/CreateAccount/index.js
  pwa/src/RootComponents/CreateAccount/inputMessage.module.css
  pwa/src/RootComponents/CreateAccount/mutations.gql.js
  pwa/src/RootComponents/CreateAccount/signup.js
  pwa/src/RootComponents/CreateAccount/signup.module.css
  pwa/src/RootComponents/CreateAccount/textInput.module.css
  pwa/src/components/Button/button.js
  pwa/src/components/Field/field.js
  pwa/src/components/Password/password.js
  pwa/src/components/Password/passwordButton.module.css
  pwa/src/components/TextInput/textInput.js
  pwa/src/talons/CreateAccount/useCreateAccount.js
  pwa/webpack.config.js
  pwa/yarn.lock
  scripts/pwa-dist/1.js
  scripts/pwa-dist/3.js
  scripts/pwa-dist/4.js
  scripts/pwa-dist/5.js
  scripts/pwa-dist/6.js
  scripts/pwa-dist/account.js
  scripts/pwa-dist/account.js.map
  scripts/pwa-dist/cart.js
  scripts/pwa-dist/cart.js.map
  scripts/pwa-dist/checkout.js
  scripts/pwa-dist/checkout.js.map
  scripts/pwa-dist/client.js
  scripts/pwa-dist/client.js.map
  scripts/pwa-dist/login.js
  scripts/pwa-dist/login.js.map
  scripts/pwa-dist/signup.js
  scripts/pwa-dist/signup.js.map
  scripts/pwa-dist/vendors.js
Labels: commerce
