Repository hlxsites/maidenform, pull requests merged in 2023-02, with the labels that each got.

#115 add improved icon loading
  blocks/header/header.css
  blocks/product-details/product-details.css
  icons/dropdown.svg
  scripts/lib-franklin.js
  styles/styles.css
Labels: bug

#113 PRecs intial commit
  blocks/product-recommendation-v2/product-recommendation-v2.css
  blocks/product-recommendation-v2/product-recommendation-v2.js
  scripts/commerce-events-sdk.js
  scripts/scripts.js
Labels: commerce

#125 Update Sidekick config for CDN
  tools/sidekick/config.json
Labels: integrations

#127 add action to sync product data to sitemap
  .github/actions/index-products/action.yaml
  .github/actions/index-products/index.js
  .github/workflows/sync-commerce.yaml
  .gitignore
  helix-sitemap.yaml
  sitemap-index.xml
Labels: commerce

#133 Fix sitemap sync
  .github/actions/index-products/action.yaml
  .github/ci/index-products.js
  .github/workflows/sync-commerce.yaml
Labels: bug

#129 fetch product ratings from bazaarvoice
  blocks/product-list-page/product-list-page.js
  scripts/commerce.js
Labels: integrations

#131 Update metadata import with new URL format and endpoint
  tools/bulk-metadata/bulk-metadata.js
  tools/bulk-metadata/package-lock.json
  tools/bulk-metadata/package.json
Labels: commerce

#134 Update URL format for sitemap redirect
  tools/sitemap-redirect/sitemap-redirect.js
Labels: commerce

#137 add url parameter to skip delayed script
  scripts/scripts.js
Labels: integrations
