Repository hlxsites/maidenform, pull requests merged in 2023-01, with the labels that each got.

#70 Make footer-links block collapsible on mobile
  blocks/copyright/copyright.css
  blocks/footer-banner/footer-banner.css
  blocks/footer-links/footer-links.css
  blocks/footer-links/footer-links.js
  blocks/newsletter/newsletter.css
  blocks/promo-banner/promo-banner.css
  styles/styles.css
Labels: bug

#69 Added design of PLP
  blocks/product-list-page/product-list-page.css
  blocks/product-list-page/product-list-page.js
  blocks/shop-by-style/shop-by-style.css
  icons/arrow-thick.svg
  icons/close-gray.svg
  icons/icon-quick-view.svg
  icons/rounded-triangle.svg
  styles/styles.css
Labels: frontend

#75 px to relative units
  styles/styles.css
Labels: accessibility

#77 Add folder mapping for products
  fstab.yaml
Labels: commerce

#79 Fix padding in navigation
  blocks/header/header.css
Labels: bug

#80 Improve accessibility of modal
  blocks/footer-banner/footer-banner.js
  blocks/promo-banner/promo-banner.js
  styles/styles.css
Labels: accessibility

#74 PDP
  blocks/product-details/product-details.css
  blocks/product-details/product-details.js
  icons/caret-down-fill.svg
  icons/caret-left-fill.svg
  icons/caret-right-fill.svg
  icons/caret-up-fill.svg
  icons/chevron-right.svg
  icons/envelope.svg
  icons/size-disabled.svg
  icons/star-fill.svg
  icons/star-half.svg
  icons/star.svg
  styles/styles.css
Labels: frontend, commerce

#83 Optimize video loading of hero-video block
  blocks/hero-video/hero-video.js
Labels: bug

#86 add block picker plugin
  .eslintignore
  .gitignore
  tools/block-picker/dist/index.3ccc1b60.css
  tools/block-picker/dist/index.3ccc1b60.css.map
  tools/block-picker/dist/index.713085d0.js
  tools/block-picker/dist/index.713085d0.js.map
  tools/block-picker/dist/index.html
  tools/block-picker/package-lock.json
  tools/block-picker/package.json
  tools/block-picker/src/copy-utils.js
  tools/block-picker/src/index.html
  tools/block-picker/src/index.js
  tools/block-picker/src/picker.js
  tools/block-picker/src/styles.css
  tools/sidekick/config.json
Labels: authoring

#55 adding commerce sidekick extension
  .eslintignore
  tools/picker/dist/index.6897f79f.css
  tools/picker/dist/index.6897f79f.css.map
  tools/picker/dist/index.9ace5cee.js
  tools/picker/dist/index.9ace5cee.js.map
  tools/picker/dist/index.html
  tools/picker/package-lock.json
  tools/picker/package.json
  tools/picker/src/index.html
  tools/picker/src/index.js
  tools/picker/src/picker.js
  tools/picker/src/queries/categories.graphql.js
  tools/picker/src/queries/category.graphql.js
  tools/picker/src/queries/products.graphql.js
  tools/picker/src/styles.css
  tools/sidekick/config.json
Labels: commerce, authoring

#85 Product Recommendations (Sitecore / Reflektion)
  .eslintignore
  blocks/header/header.js
  blocks/product-recommendation/product-recommendation.css
  blocks/product-recommendation/product-recommendation.js
  scripts/delayed.js
  scripts/jquery.min.js
Labels: integrations

#91 Pdp preact
  .eslintignore
  blocks/product-details/Icon.js
  blocks/product-details/ProductDetailsCarousel.js
  blocks/product-details/ProductDetailsSidebar.js
  blocks/product-details/product-details.js
  scripts/htm.js
  scripts/preact.js
Labels: commerce

#94 Pdp Loading Effect
  blocks/product-details/Icon.js
  blocks/product-details/ProductDetailsCarousel.js
  blocks/product-details/ProductDetailsShimmer.js
  blocks/product-details/ProductDetailsSidebar.js
  blocks/product-details/product-details.css
  blocks/product-details/product-details.js
Labels: frontend, commerce

#96 Product List Page in Preact
  blocks/product-list-page/FacetList.js
  blocks/product-list-page/ProductList.js
  blocks/product-list-page/product-list-page.css
  blocks/product-list-page/product-list-page.js
  styles/styles.css
Labels: frontend, commerce

#95 add keyboard and focus events to promo banner
  blocks/footer-banner/footer-banner.js
  blocks/promo-banner/promo-banner.js
Labels: accessibility

#99 enable keyboard navigation in nav
  blocks/header/header.css
  blocks/header/header.js
Labels: accessibility

#104 make touch events passive
  blocks/footer-banner/footer-banner.js
Labels: accessibility

#98 Optimize loading of reflektion library
  blocks/header/header.js
  blocks/product-recommendation/product-recommendation.js
  scripts/delayed.js
  scripts/reflektion.js
Labels: bug

#107 add fragment block
  .stylelintignore
  blocks/footer/footer.js
  blocks/fragment/fragment.css
  blocks/fragment/fragment.js
  scripts/scripts.js
Labels: authoring

#106 generate bulk metadata sheet - initial version
  .eslintignore
  tools/bulk-metadata/bulk-metadata.js
  tools/bulk-metadata/package.json
  tools/bulk-metadata/queries/products.graphql.js
Labels: commerce

#108 add enrichment fragments
  .stylelintignore
  blocks/product-enrichment/product-enrichment.css
  blocks/product-enrichment/product-enrichment.js
  scripts/scripts.js
Labels: commerce, authoring

#112 Environment Specific Configurations - POC
  blocks/environment/environment.css
  blocks/environment/environment.js
  scripts/configs.js
Labels: authoring
