Repository hlxsites/maidenform, pull requests merged in 2023-03, with the labels that each got.

#149 Fix mobile CLS of hero video block
  blocks/hero-video/hero-video.css
  blocks/hero-video/hero-video.js
Labels: authoring

#152 Magento recommendations
  .eslintignore
  blocks/product-details/product-details.js
  blocks/product-recommendation-v2/product-recommendation-v2.css
  blocks/product-recommendation-v2/product-recommendation-v2.js
  blocks/product-recommendation/product-recommendation.css
  blocks/product-recommendation/product-recommendation.js
  scripts/magento-recommendations-sdk.js
  scripts/mse-utils.js
  scripts/product.js
  scripts/scripts.js
Labels: commerce

#119 Product reviews and questions
  .stylelintignore
  blocks/curalate-gallery/curalate-gallery.js
  blocks/product-reviews/product-reviews.css
  blocks/product-reviews/product-reviews.js
  scripts/bazaarvoice.js
  scripts/product.js
  styles/bazaarvoice.css
Labels: integrations

#136 PLP + Search using Live Search
  blocks/product-details/ProductDetailsCarousel.js
  blocks/product-details/ProductDetailsSidebar.js
  blocks/product-details/product-details.css
  blocks/product-details/product-details.js
  blocks/product-list-page/FacetList.js
  blocks/product-list-page/ProductList.js
  blocks/product-list-page/product-list-page.css
  blocks/product-list-page/product-list-page.js
  blocks/product-list-page/productSearch.graphql.js
  blocks/product-reviews/product-reviews.js
  scripts/commerce.js
  scripts/product.js
  scripts/scripts.js
  styles/styles.css
Labels: commerce

#161 add breadcrumb autoblocking
  blocks/breadcrumb/breadcrumb.css
  blocks/breadcrumb/breadcrumb.js
  blocks/product-details/product-details.css
  scripts/commerce.js
  scripts/scripts.js
  styles/styles.css
Labels: commerce, authoring

#168 fix: logo altered elements
  scripts/lib-franklin.js
Labels: bug

#151 Add product image importer script
  .gitignore
  tools/bulk-metadata/bulk-metadata.js
  tools/product-image-importer/package.json
  tools/product-image-importer/product-image-importer.js
  tools/product-image-importer/queries/products.graphql.js
Labels: commerce

#170 Update importer to respect new breadcrumb logic
  tools/importer/import.js
Labels: authoring

#167 implement link rewriting with product sku query
  scripts/commerce.js
  scripts/reflektion.js
Labels: bug

#172 Minicart Component
  blocks/header/header.css
  blocks/header/header.js
  blocks/product-details/product-details.js
  icons/edit.svg
  icons/loader.gif
  icons/trash.svg
  scripts/cart/api.js
  scripts/cart/init-cart.js
  scripts/cart/minicart.js
  scripts/commerce.js
  scripts/mse-utils.js
  styles/minicart.css
Labels: commerce

#180 fix: link in menu items without children
  blocks/header/header.css
  blocks/header/header.js
Labels: bug
